/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.Acoes;
import DAO.Volta;
import Model.Pessoa;
import java.awt.Color;
import java.awt.Component;
import java.io.IOException;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class Tela8 extends javax.swing.JFrame implements Volta {
     private static long minutos_permanecidos;
    /**
     * Creates new form Tela03
     */
    public Tela8() {
        initComponents();
    }
    int erros;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        resp02 = new javax.swing.JTextField();
        Prosseguir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        vida3 = new javax.swing.JLabel();
        vida1 = new javax.swing.JLabel();
        vida2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Easy?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 10, 80, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fase 03.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 50, 340, 230);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Resposta:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 310, 60, 20);

        resp02.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                resp02KeyReleased(evt);
            }
        });
        getContentPane().add(resp02);
        resp02.setBounds(140, 310, 160, 20);

        Prosseguir.setText("Prosseguir");
        Prosseguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsseguirActionPerformed(evt);
            }
        });
        getContentPane().add(Prosseguir);
        Prosseguir.setBounds(70, 350, 110, 29);

        jButton2.setText("Desistir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 350, 120, 29);

        vida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/coracao.png"))); // NOI18N
        getContentPane().add(vida3);
        vida3.setBounds(840, 30, 100, 100);

        vida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/coracao.png"))); // NOI18N
        getContentPane().add(vida1);
        vida1.setBounds(620, 30, 100, 100);

        vida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/coracao.png"))); // NOI18N
        getContentPane().add(vida2);
        vida2.setBounds(730, 30, 100, 100);

        jLabel4.setText("vidas");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(510, 50, 34, 17);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resp02KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resp02KeyReleased
        if (resp02.getText().equals("Central Park")) {
            resp02.setBackground(Color.GREEN);
            JOptionPane.showMessageDialog(null, "resposta certa");

        } else {
            resp02.requestFocus();
        }
    }//GEN-LAST:event_resp02KeyReleased

    private void ProsseguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsseguirActionPerformed
        if (resp02.getText().equals("Central Park")) {
            if (erros == 1) {
                Pessoa.setPontuacao(Pessoa.getPontuacao() + 8);
            } else if (erros == 2) {
                Pessoa.setPontuacao(Pessoa.getPontuacao() + 6);
            } else {
                Pessoa.setPontuacao(Pessoa.getPontuacao() + 10);
            }
            this.dispose();
             Date data_saida = new Date();
             Pessoa pessoa = new Pessoa(data_saida);
             
        
             minutos_permanecidos = (((data_saida.getTime() - Login.getPessoa().getEntrada().getTime()) / 1000) / 60);
             Login.p.setAlgo( minutos_permanecidos);
             System.out.println("Saida:" + Pessoa.getSaida());
             System.out.println("Tempo de jogo em minutos:" + Login.p.getAlgo());
           try {
               Acoes.escreverControle("Saida:" +  Pessoa.getSaida());
               Acoes.escreverControle("Tempo de jogo em minutos:" + minutos_permanecidos);
               //Acoes.escreverControle("Codigo de Segurança:" + Login.getPessoa().getGerador());
           } catch (IOException ex) {
               JOptionPane.showMessageDialog(null, ex.getMessage());
           }
            Ganhou ganhar = new Ganhou();
            ganhar.setVisible(true);
        } else {
            erros++;
            this.volta();
        }

    }//GEN-LAST:event_ProsseguirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int confirm = JOptionPane.showConfirmDialog((Component) evt.getSource(),
                "Deseja Realmente Desistir?",
                "Sim - Nao",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Sua Pontuaçao foi de:" + Pessoa.getPontuacao() + "\n" + "Obrigado(a) por participar do nosso jogo!!");
            this.dispose();
            Menu menu = new Menu();
            menu.setVisible(true);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Prosseguir;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField resp02;
    private javax.swing.JLabel vida1;
    private javax.swing.JLabel vida2;
    private javax.swing.JLabel vida3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void volta() {
        if (erros == 1) {
            vida3.setVisible(false);
        } else if (erros == 2) {
            vida3.setVisible(false);
            vida2.setVisible(false);
        } else if (erros == 3) {
            vida3.setVisible(false);
            vida2.setVisible(false);
            vida1.setVisible(false);

            JOptionPane.showMessageDialog(null, "Game Over!");
            this.setVisible(false);
            Fase1 fase1 = new Fase1();

        }
    }
}
