/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.Volta;
import Model.Pessoa;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class Tela6 extends javax.swing.JFrame implements Volta {

    /**
     * Creates new form tela01
     */
    public Tela6() {
        super("Tela 6");
        initComponents();
    }
    int erros;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtb = new javax.swing.JFormattedTextField();
        txta = new javax.swing.JFormattedTextField();
        txtd = new javax.swing.JFormattedTextField();
        txtf = new javax.swing.JFormattedTextField();
        txtg = new javax.swing.JFormattedTextField();
        txth = new javax.swing.JFormattedTextField();
        varf = new javax.swing.JFormattedTextField();
        varg = new javax.swing.JFormattedTextField();
        varh = new javax.swing.JFormattedTextField();
        vari = new javax.swing.JFormattedTextField();
        vara = new javax.swing.JFormattedTextField();
        txtz = new javax.swing.JFormattedTextField();
        varj = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        vida1 = new javax.swing.JLabel();
        vida2 = new javax.swing.JLabel();
        vida3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/deserto1a.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(918, 605, 152, 105);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/torneira1a.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(128, 11, 119, 152);

        try {
            txtb.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbKeyReleased(evt);
            }
        });
        getContentPane().add(txtb);
        txtb.setBounds(143, 255, 90, 80);

        try {
            txta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtaKeyReleased(evt);
            }
        });
        getContentPane().add(txta);
        txta.setBounds(143, 169, 90, 80);

        try {
            txtd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdKeyReleased(evt);
            }
        });
        getContentPane().add(txtd);
        txtd.setBounds(339, 341, 90, 80);

        try {
            txtf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtfKeyReleased(evt);
            }
        });
        getContentPane().add(txtf);
        txtf.setBounds(339, 427, 90, 80);

        try {
            txtg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtgKeyReleased(evt);
            }
        });
        getContentPane().add(txtg);
        txtg.setBounds(339, 513, 90, 80);

        try {
            txth.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txthKeyReleased(evt);
            }
        });
        getContentPane().add(txth);
        txth.setBounds(339, 605, 90, 80);

        varf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                varfKeyReleased(evt);
            }
        });
        getContentPane().add(varf);
        varf.setBounds(435, 605, 91, 80);

        varg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vargKeyReleased(evt);
            }
        });
        getContentPane().add(varg);
        varg.setBounds(532, 605, 91, 80);

        varh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                varhKeyReleased(evt);
            }
        });
        getContentPane().add(varh);
        varh.setBounds(629, 605, 91, 80);

        vari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                variKeyReleased(evt);
            }
        });
        getContentPane().add(vari);
        vari.setBounds(726, 605, 91, 80);

        vara.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                varaKeyReleased(evt);
            }
        });
        getContentPane().add(vara);
        vara.setBounds(239, 255, 91, 80);

        try {
            txtz.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtz.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtzKeyReleased(evt);
            }
        });
        getContentPane().add(txtz);
        txtz.setBounds(339, 255, 90, 80);

        varj.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                varjKeyReleased(evt);
            }
        });
        getContentPane().add(varj);
        varj.setBounds(823, 605, 91, 80);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Faz com que a água chegue ao deserto com um sistema de encanamentos");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 30, 690, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedra1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 340, 110, 110);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pedra2.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(450, 250, 120, 100);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("com a menor rota possível");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(450, 50, 290, 40);

        jLabel7.setText("dica: utilize o teclado");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 710, 110, 17);

        vida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/coracao.png"))); // NOI18N
        getContentPane().add(vida1);
        vida1.setBounds(680, 100, 100, 90);

        vida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/coracao.png"))); // NOI18N
        getContentPane().add(vida2);
        vida2.setBounds(810, 100, 100, 90);

        vida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/coracao.png"))); // NOI18N
        getContentPane().add(vida3);
        vida3.setBounds(930, 100, 100, 90);

        jButton1.setText("Desistir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 693, 100, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel11.setText("Vidas");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(560, 110, 60, 30);
        jLabel6.setForeground(Color.WHITE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //esconder
        txtb.setVisible(false);
        txtb.setVisible(false);
        txtd.setVisible(false);
        txtf.setVisible(false);
        txtg.setVisible(false);
        txth.setVisible(false);
        txtz.setVisible(false);
        vara.setVisible(false);
        varf.setVisible(false);
        varg.setVisible(false);
        varh.setVisible(false);
        vari.setVisible(false);
        varj.setVisible(false);

    }//GEN-LAST:event_formWindowOpened

    private void txtaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaKeyReleased
        // verificar se digitou rota correta
        if (txta.getText().equals("I")) {
            txta.setBackground(Color.BLUE);
            txtb.setVisible(true);
            txtb.requestFocus();
        } else {
            txta.setBackground(Color.RED);
            txta.setText(null);
            txta.requestFocus();
            erros++;
            this.volta();
        }
    }//GEN-LAST:event_txtaKeyReleased

    private void txtbKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbKeyReleased
        if (txtb.getText().equals("L")) {
            txtb.setBackground(Color.BLUE);
            vara.setVisible(true);
            vara.requestFocus();

        } else {
            txtb.setBackground(Color.RED);
            txtb.setText(null);
            txtb.requestFocus();
            erros++;
            this.volta();
        }
    }//GEN-LAST:event_txtbKeyReleased

    private void varaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_varaKeyReleased
        if (vara.getText().equals("-")) {
            vara.setBackground(Color.BLUE);
            txtz.setVisible(true);
            txtz.requestFocus();

        } else {
            vara.setBackground(Color.RED);
            vara.setText(null);
            vara.requestFocus();
            erros++;
            this.volta();
        }
    }//GEN-LAST:event_varaKeyReleased

    private void txtzKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtzKeyReleased
        if (txtz.getText().equals("T")) {
            txtz.setBackground(Color.BLUE);
            txtd.setVisible(true);
            txtd.requestFocus();

        } else {
            txtz.setBackground(Color.RED);
            txtz.setText(null);
            txtz.requestFocus();
            erros++;
            this.volta();
        }
    }//GEN-LAST:event_txtzKeyReleased

    private void txtdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdKeyReleased
        if (txtd.getText().equals("I")) {
            txtd.setBackground(Color.BLUE);
            txtf.setVisible(true);
            txtf.requestFocus();

        } else {
            txtd.setBackground(Color.RED);
            txtd.setText(null);
            txtd.requestFocus();
            erros++;
            this.volta();
        }
    }//GEN-LAST:event_txtdKeyReleased

    private void txtfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfKeyReleased
        if (txtf.getText().equals("I")) {
            txtf.setBackground(Color.BLUE);
            txtg.setVisible(true);
            txtg.requestFocus();

        } else {
            txtf.setBackground(Color.RED);
            txtf.setText(null);
            txtf.requestFocus();
            erros++;
            this.volta();
        }
    }//GEN-LAST:event_txtfKeyReleased

    private void txtgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgKeyReleased
        if (txtg.getText().equals("I")) {
            txtg.setBackground(Color.BLUE);
            txth.setVisible(true);
            txth.requestFocus();

        } else {
            txtg.setBackground(Color.RED);
            txtg.setText(null);
            txtg.requestFocus();
            erros++;
            this.volta();
        }
    }//GEN-LAST:event_txtgKeyReleased

    private void txthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthKeyReleased
        if (txth.getText().equals("L")) {
            txth.setBackground(Color.BLUE);
            varf.setVisible(true);
            varf.requestFocus();

        } else {
            txth.setBackground(Color.RED);
            txth.setText(null);
            txth.requestFocus();
            erros++;
            this.volta();
        }
    }//GEN-LAST:event_txthKeyReleased

    private void varfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_varfKeyReleased
        if (varf.getText().equals("-")) {
            varf.setBackground(Color.BLUE);
            varg.setVisible(true);
            varg.requestFocus();

        } else {
            varf.setBackground(Color.RED);
            varf.setText(null);
            varf.requestFocus();
            erros++;
            this.volta();
        }
    }//GEN-LAST:event_varfKeyReleased

    private void vargKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vargKeyReleased
        if (varg.getText().equals("-")) {
            varg.setBackground(Color.BLUE);
            varh.setVisible(true);
            varh.requestFocus();

        } else {
            varg.setBackground(Color.RED);
            varg.setText(null);
            varg.requestFocus();
            erros++;
            this.volta();
        }
    }//GEN-LAST:event_vargKeyReleased

    private void varhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_varhKeyReleased
        if (varh.getText().equals("-")) {
            varh.setBackground(Color.BLUE);
            vari.setVisible(true);
            vari.requestFocus();

        } else {
            varh.setBackground(Color.RED);
            varh.setText(null);
            varh.requestFocus();
            erros++;
            this.volta();
        }
    }//GEN-LAST:event_varhKeyReleased

    private void variKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_variKeyReleased
        if (vari.getText().equals("-")) {
            vari.setBackground(Color.BLUE);
            varj.setVisible(true);
            varj.requestFocus();

        } else {
            vari.setBackground(Color.RED);
            vari.setText(null);
            vari.requestFocus();
            erros++;
            this.volta();
        }
    }//GEN-LAST:event_variKeyReleased

    private void varjKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_varjKeyReleased
        if (varj.getText().equals("-")) {
            varj.setBackground(Color.BLUE);
            JOptionPane.showMessageDialog(null, "parabens, passou de fase");
            if (erros == 1) {
                Pessoa.setPontuacao(Pessoa.getPontuacao() + 8);
            } else if (erros == 2) {
                Pessoa.setPontuacao(Pessoa.getPontuacao() + 6);
            } else {
                Pessoa.setPontuacao(Pessoa.getPontuacao() + 10);
            }
            this.dispose();
            Tela7 tela7 = new Tela7();
            tela7.setVisible(true);

        } else {
            varj.setBackground(Color.RED);
            varj.setText(null);
            varj.requestFocus();
            erros++;
            this.volta();
        }
    }//GEN-LAST:event_varjKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int confirm = JOptionPane.showConfirmDialog((Component) evt.getSource(),
                "Deseja Realmente Desistir?",
                "Sim - Nao",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(null, "Sua Pontuaçao foi de:" + Pessoa.getPontuacao() + "\n" + "Obrigado(a) por participar do nosso jogo!!");
            this.dispose();
            Menu menu = new Menu();
            menu.setVisible(true);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JFormattedTextField txta;
    private javax.swing.JFormattedTextField txtb;
    private javax.swing.JFormattedTextField txtd;
    private javax.swing.JFormattedTextField txtf;
    private javax.swing.JFormattedTextField txtg;
    private javax.swing.JFormattedTextField txth;
    private javax.swing.JFormattedTextField txtz;
    private javax.swing.JFormattedTextField vara;
    private javax.swing.JFormattedTextField varf;
    private javax.swing.JFormattedTextField varg;
    private javax.swing.JFormattedTextField varh;
    private javax.swing.JFormattedTextField vari;
    private javax.swing.JFormattedTextField varj;
    private javax.swing.JLabel vida1;
    private javax.swing.JLabel vida2;
    private javax.swing.JLabel vida3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void volta() {
        if (erros == 1) {
            vida3.setVisible(false);
        } else if (erros == 2) {
            vida3.setVisible(false);
            vida2.setVisible(false);
        } else if (erros == 3) {
            vida3.setVisible(false);
            vida2.setVisible(false);
            vida1.setVisible(false);

            JOptionPane.showMessageDialog(null, "Game Over!");
            this.setVisible(false);
            Fase1 fase1 = new Fase1();

        }
    }
}
